WADFC/Controllers/CMSController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WADFC.Models;

namespace WADFC.Controllers
{
    [Authorize(Roles = "Manager")]
    public class CMSController : Controller
    {
        private readonly ILogger<CMSController> _logger;

        private readonly ApplicationDbContext _context;

        public CMSController(ILogger<CMSController> logger, ApplicationDbContext context)
        {
            _context = context;
            _logger = logger;
        }

        public IActionResult Index()
        {
            List<Event> allEventsModel = _context.Events.ToList();

            return View(allEventsModel);
        }

        [HttpGet]
        public IActionResult AddEvent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddEvent(EventForm model)
        {
            if (ModelState.IsValid)
            {

                Event newEvent = new Event
                {
                    EventTitle = model.EventTitle,
                    Location = model.Location,
                    EventImage = model.EventImage,
                    Date = DateTime.Now,
                    // Date = model.Date, // TODO: Check how to implement this
                    Completed = "Y"
                };
                _context.Add(newEvent);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public IActionResult UpdateEvent(int id)
        {
            Event model = _context.Events.Find(id);
            EventForm formModel = new EventForm
            {
                EventID = model.EventID,
                EventTitle = model.EventTitle,
                Location = model.Location,
                EventImage = model.EventImage,
                Date = model.Date
            };
            return View(formModel);
        }

        [HttpPost]
        public IActionResult UpdateEvent(EventForm model)
        {
            if (ModelState.IsValid)
            {
                Event editEvent = new Event
                {
                    EventID = model.EventID,
                    EventTitle = model.EventTitle,
                    Location = model.Location,
                    EventImage = model.EventImage,
                    Date = model.Date,
                    Completed = "Y"
                };
                _context.Events.Update(editEvent);

                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult AllFights(int id)
        {
            List<EventDetails> modelList = new List<EventDetails>();
            var query = (
              from fght in _context.Fights
              join f in _context.Fighters
              on fght.FighterAID equals f.FighterID
              join f2 in _context.Fighters
              on fght.FighterBID equals f2.FighterID
              join e in _context.Events
              on fght.EventID equals e.EventID
              where e.EventID == id
              select new
              {
                  FightID = fght.FightID,
                  EventTitle = e.EventTitle,
                  Round = fght.Round,
                  Method = fght.Method,
                  WinnerName = fght.Winner,
                  FighterAName = f.FirstName + " " + f.Surname,
                  FighterBName = f2.FirstName + " " + f2.Surname
              }).ToList();

            foreach (var item in query)
            {
                modelList.Add(new EventDetails()
                {
                    EventID = id,
                    FightID = item.FightID,
                    EventTitle = item.EventTitle,
                    Round = item.Round,
                    Method = item.Method,
                    WinnerName = item.WinnerName,
                    FighterAName = item.FighterAName,
                    FighterBName = item.FighterBName
                });
            }

            if (modelList.Count < 1)
            {

                Event model = _context.Events.Find(id);

                modelList.Add(new EventDetails()
                {
                    EventID = id,
                    EventTitle = model.EventTitle,
                    FighterAName = "NONE",
                    FighterBName = "NONE"
                });
            }

            return View(modelList);
        }

        [HttpGet]
        public IActionResult AllFighters()
        {
            List<Fighter> allFightersModel = _context.Fighters.ToList();
            return View(allFightersModel);
        }

        [HttpGet]
        public IActionResult AddFighter()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddFighter(FighterForm model)
        {
            if (ModelState.IsValid)
            {
                Fighter newFighter = new Fighter
                {
                    FirstName = model.FirstName,
                    Surname = model.Surname,
                    DOB = DateTime.Now,
                    // DOB = model.Date, // TODO: Check how to implement this
                    Height = model.Height,
                    Weight = model.Weight,
                    Reach = model.Reach,
                    Win = model.Win,
                    Loss = model.Loss,
                    Draw = model.Draw,
                    NoContest = model.NoContest,
                    Stance = "\"" + model.Stance + "\""
                };
                _context.Add(newFighter);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public IActionResult EditFighter(int id)
        {
            Fighter model = _context.Fighters.Find(id);
            FighterForm formModel = new FighterForm
            {
                FighterID = model.FighterID,
                FirstName = model.FirstName,
                Surname = model.Surname,
                Win = model.Win,
                Loss = model.Loss,
                Draw = model.Draw,
                NoContest = model.NoContest,
                Height = model.Height,
                Weight = model.Weight,
                Reach = model.Reach,
                Stance = model.Stance, 
                DOB = model.DOB
            };
            return View(formModel);
        }

        [HttpPost]
        public IActionResult EditFighter(FighterForm model)
        {
            if (ModelState.IsValid)
            {
                Fighter editFighter = new Fighter
                {
                    FighterID = model.FighterID,
                    FirstName = model.FirstName,
                    Surname = model.Surname,
                    Win = model.Win,
                    Loss = model.Loss,
                    Draw = model.Draw,
                    NoContest = model.NoContest,
                    Height = model.Height,
                    Weight = model.Weight,
                    Reach = model.Reach,
                    Stance = "\"" + model.Stance + "\"",
                    DOB = model.DOB
                };
                _context.Fighters.Update(editFighter);

                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult AddFight(int id)
        {
            Event model = _context.Events.Find(id);
            EventFighters eventFighters = new EventFighters
            {

                EventID = model.EventID,
                FightersList = _context.Fighters.ToList(),
                NewFightForm = new FightForm()
            };

            eventFighters.NewFightForm.EventID = id;
            return View(eventFighters);
        }

        [HttpPost]
        public IActionResult AddFight(EventFighters model, int id)
        {
            model.EventID = id;
            if (ModelState.IsValid)
            {
                if (model.NewFightForm.FighterAID != model.NewFightForm.FighterBID)
                {
                    Fight newFight = new Fight
                    {
                        EventID = model.EventID,
                        FighterAID = model.NewFightForm.FighterAID,
                        FighterBID = model.NewFightForm.FighterBID,
                        Division = model.NewFightForm.Division,
                        Winner = model.NewFightForm.Winner,
                        Method = model.NewFightForm.Method,
                        Round = model.NewFightForm.Round
                    };
                    _context.Add(newFight);
                    _context.SaveChanges();
                    return RedirectToAction(nameof(Index));
                }
            }

            return AddFight(id);
        }

        [HttpGet]
        public IActionResult UpdateFight(int id)
        {

            Fight fightModel = _context.Fights.Find(id);
            Event eventModel = _context.Events.Find(fightModel.EventID);

            FightDetails fightDetails = new FightDetails
            {
                FightID = id,
                EventID = eventModel.EventID,
                Winner = fightModel.Winner,
                Round = fightModel.Round,
                Method = fightModel.Method,
                Divisions = fightModel.Division,
                FighterA = _context.Fighters.Find(fightModel.FighterAID),
                FighterB = _context.Fighters.Find(fightModel.FighterBID),
                FightersList = _context.Fighters.ToList(),
                NewFightForm = new FightForm()
            };

WADFC/Views/Shared/_CMS.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CMS | WADFC</title>
    <link rel="stylesheet" href="~/css/cms.css" />
</head>
<body>
    <header>
        <div class="innerHeader">
            <div>
                <h1>Content Management System @ViewData["PageHeading"]</h1>
                <nav>
                    <ul>
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="CMS" asp-action="Index">EventsCMS</a></li>
                        <li><a asp-controller="CMS" asp-action="AllFighters">FightersCMS</a></li>
                    </ul>
                </nav>
            </div>
            @if (User.Identity.IsAuthenticated)
            {
<div class="login">
    <p>Welcome @User.Identity.Name</p>
    <form asp-controller="Security" asp-action="SignOut" method="post">
        <button type="submit" class="delete">Sign Out</button>
    </form>
</div>            }
        </div>
    </header>
    <main>
        @RenderBody()
    </main>
    <footer>
    </footer>
    @*@RenderSection("Scripts", required: false)*@
    @RenderSection("MyScripts", required: false)
</body>
</html>

WADFC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="UFC fights from 2020-2021">
    <meta name="keywords" content="UFC,fights,fighters,FightNight">
    <meta name="author" content="Girts Jermacans">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/mobile.css" />
    <link rel="stylesheet" media="only screen and (min-width : 720px)" href="~/css/desktop.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
</head>
<body>
    <div class="container">
        <header>
            <h1>WADFC</h1>
        </header>
        <main>
            <div class="searchBurgerLine">
                <div class="hideForDesktop">
                    <form action="" id="unknownSearch">
                        <input type="text" name="searchString" id="SearchString"/>
                        <button type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </form>
                </div>
                <div class="burgerMenu">
                    <div class="bars">
                        <div class="bar1"></div>
                        <div class="bar2"></div>
                        <div class="bar3"></div>
                    </div>
                </div>
            </div>
            <nav>
                <ul>
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Home" asp-action="AllEvents">Events</a></li>
                    <li><a asp-controller="Home" asp-action="AllFighters">Fighters</a></li>
                    <li><a asp-controller="Home" asp-action="AdvancedSearch">Search</a></li>
                    <li><a asp-controller="CMS" asp-action="Index">CMS</a></li>
                </ul>
            </nav>
            <h1 class="pageHeading">@ViewData["PageHeading"]</h1>
            @RenderBody()
        </main>
        <footer>
            <p>&copy; 2021, Girts Jermacans</p>
        </footer>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    @RenderSection("MyScripts", required: false)
</body>

</html>